---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: metrics-info
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metrics-info
  template:
    metadata:
      labels:
        app: metrics-info
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: metrics-infod
        image: quay.io/brice/metrics-demo:v4-subscription-service
